// <auto-generated />
using System;
using EFDataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFDataAccess.Migrations
{
    [DbContext(typeof(PhoTexBlogContext))]
    [Migration("20200630153414_added usecases")]
    partial class addedusecases
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9105),
                            PostId = 23,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 2,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9523),
                            PostId = 7,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 3,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9537),
                            PostId = 6,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 4,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9546),
                            PostId = 6,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 5,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9555),
                            PostId = 9,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 6,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9573),
                            PostId = 23,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 7,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9581),
                            PostId = 20,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 8,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9589),
                            PostId = 16,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 9,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9598),
                            PostId = 11,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 10,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9608),
                            PostId = 3,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 11,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9617),
                            PostId = 15,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 12,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9625),
                            PostId = 19,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 13,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9633),
                            PostId = 20,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 14,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9641),
                            PostId = 3,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 15,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9650),
                            PostId = 13,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 16,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9658),
                            PostId = 5,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 17,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9666),
                            PostId = 18,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 18,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9677),
                            PostId = 22,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 19,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9685),
                            PostId = 23,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 20,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9694),
                            PostId = 3,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 21,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9702),
                            PostId = 18,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 22,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9710),
                            PostId = 12,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 23,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9719),
                            PostId = 13,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 24,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9727),
                            PostId = 22,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 25,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9735),
                            PostId = 19,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 26,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9746),
                            PostId = 9,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 27,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9754),
                            PostId = 22,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 28,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9762),
                            PostId = 17,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 29,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9771),
                            PostId = 20,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 30,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9779),
                            PostId = 19,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 31,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9787),
                            PostId = 4,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 32,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9795),
                            PostId = 7,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 33,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9803),
                            PostId = 15,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 34,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9815),
                            PostId = 22,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 35,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9823),
                            PostId = 22,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 36,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9831),
                            PostId = 2,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 37,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9839),
                            PostId = 22,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 38,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9847),
                            PostId = 23,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 39,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9855),
                            PostId = 2,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 40,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9864),
                            PostId = 8,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 41,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9872),
                            PostId = 14,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 42,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9880),
                            PostId = 11,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 43,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9888),
                            PostId = 23,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 44,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9896),
                            PostId = 12,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 45,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9904),
                            PostId = 9,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 46,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9913),
                            PostId = 11,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 47,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9921),
                            PostId = 23,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 48,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9929),
                            PostId = 5,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 49,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9981),
                            PostId = 12,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 50,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9990),
                            PostId = 16,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 51,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 870, DateTimeKind.Local).AddTicks(9998),
                            PostId = 5,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 52,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(6),
                            PostId = 17,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 53,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(15),
                            PostId = 5,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 54,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(23),
                            PostId = 8,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 55,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(31),
                            PostId = 7,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 56,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(39),
                            PostId = 9,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 57,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(47),
                            PostId = 4,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 58,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(56),
                            PostId = 4,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 59,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(64),
                            PostId = 11,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 60,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(72),
                            PostId = 1,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 61,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(80),
                            PostId = 2,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 62,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(88),
                            PostId = 9,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 63,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(97),
                            PostId = 22,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 64,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(105),
                            PostId = 16,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 65,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(113),
                            PostId = 13,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 66,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(124),
                            PostId = 8,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 67,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(132),
                            PostId = 20,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 68,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(141),
                            PostId = 12,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 69,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(149),
                            PostId = 18,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 70,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(157),
                            PostId = 1,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 71,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(165),
                            PostId = 14,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 72,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(173),
                            PostId = 6,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 73,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(181),
                            PostId = 4,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 74,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(189),
                            PostId = 10,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 75,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(198),
                            PostId = 5,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 76,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(206),
                            PostId = 9,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 77,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(214),
                            PostId = 10,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 78,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(222),
                            PostId = 22,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 79,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(230),
                            PostId = 19,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 80,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(239),
                            PostId = 13,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 81,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(247),
                            PostId = 1,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 82,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(255),
                            PostId = 16,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 83,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(263),
                            PostId = 13,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 84,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(271),
                            PostId = 12,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 85,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(279),
                            PostId = 14,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 86,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(287),
                            PostId = 22,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 87,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(296),
                            PostId = 23,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 88,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(304),
                            PostId = 4,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 89,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(312),
                            PostId = 6,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 90,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(320),
                            PostId = 7,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 91,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(328),
                            PostId = 3,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 92,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(336),
                            PostId = 10,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 93,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(345),
                            PostId = 19,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 94,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(353),
                            PostId = 5,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 95,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(361),
                            PostId = 10,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 96,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(369),
                            PostId = 14,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 97,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(377),
                            PostId = 12,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 98,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(386),
                            PostId = 6,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 99,
                            CommentText = "In sit amet libero vestibulum, rutrum enim dictum, sagittis ipsum. Vestibulum at magna sagittis, gravida turpis a, luctus sapien. Duis ac ipsum ac ante iaculis rhoncus. Nullam eu urna in dolor lobortis cursus. ",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(394),
                            PostId = 14,
                            UserId = 1,
                            Visible = true
                        });
                });

            modelBuilder.Entity("Domain.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "post1post1post1post1post1post1post1post1post1post1post1post1post1post1",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9336),
                            PhotoPath = "images/1.png",
                            Title = "Post 1",
                            TopicId = 5,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 2,
                            Content = "post2post2post2post2post2post2post2post2post2post2post2",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9557),
                            PhotoPath = "images/2.png",
                            Title = "Post 2",
                            TopicId = 3,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 3,
                            Content = "post3post3post3post3post3post3post3",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9575),
                            PhotoPath = "images/3.png",
                            Title = "Post 3",
                            TopicId = 4,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 4,
                            Content = "post4post4post4post4post4post4post4post4post4post4",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9588),
                            PhotoPath = "images/4.png",
                            Title = "Post 4",
                            TopicId = 6,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 5,
                            Content = "post1post1post1post1post1post1post1post1post1post1post1post1post1post1",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9600),
                            PhotoPath = "images/5.png",
                            Title = "Post 5",
                            TopicId = 3,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 6,
                            Content = "post2post2post2post2post2post2post2post2post2",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9620),
                            PhotoPath = "images/6.png",
                            Title = "Post 6",
                            TopicId = 4,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 7,
                            Content = "post3post3post3post3post3post3post3",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9634),
                            PhotoPath = "images/7.png",
                            Title = "Post 7",
                            TopicId = 6,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 8,
                            Content = "post4post4post4post4post4post4post4post4post4",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9646),
                            PhotoPath = "images/8.png",
                            Title = "Post 8",
                            TopicId = 3,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 9,
                            Content = "post1post1post1post1post1post1post1post1",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9660),
                            PhotoPath = "images/9.png",
                            Title = "Post 9",
                            TopicId = 3,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 10,
                            Content = "post2post2post2post2post2post2post2post2post2",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9674),
                            PhotoPath = "images/10.jpg",
                            Title = "Post 10",
                            TopicId = 2,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 11,
                            Content = "post3post3post3post3post3post3post3",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9686),
                            PhotoPath = "images/11.jpg",
                            Title = "Post 11",
                            TopicId = 6,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 12,
                            Content = "post3post3post3post3post3post3post3",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9698),
                            PhotoPath = "images/12.jpg",
                            Title = "Post 12",
                            TopicId = 2,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 13,
                            Content = "post1post2post3post4",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9710),
                            PhotoPath = "images/13.jpg",
                            Title = "Post 13",
                            TopicId = 4,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 14,
                            Content = "post4post4post431",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9722),
                            PhotoPath = "images/14.jpg",
                            Title = "Post 14",
                            TopicId = 3,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 15,
                            Content = "post4post4post431",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9734),
                            PhotoPath = "images/15.jpg",
                            Title = "Post 15",
                            TopicId = 7,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 16,
                            Content = "post1post1post2post3",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9745),
                            PhotoPath = "images/16.jpg",
                            Title = "Post 16",
                            TopicId = 4,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 17,
                            Content = "post1post1post2post3post2",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9756),
                            PhotoPath = "images/17.jpg",
                            Title = "Post 17",
                            TopicId = 5,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 18,
                            Content = "post4post4post4post4post4post4post4",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9771),
                            PhotoPath = "images/18.jpg",
                            Title = "Post 18",
                            TopicId = 5,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 19,
                            Content = "post2post2post2post2",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9820),
                            PhotoPath = "images/19.jpg",
                            Title = "Post 19",
                            TopicId = 1,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 20,
                            Content = "post12post1post1post1post1",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9832),
                            PhotoPath = "images/20.jpg",
                            Title = "Post 20",
                            TopicId = 6,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 21,
                            Content = "post12post1post1post1post4",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9844),
                            PhotoPath = "images/21.jpg",
                            Title = "Post 21",
                            TopicId = 4,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 22,
                            Content = "post1post2post3post4",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9855),
                            PhotoPath = "images/22.jpg",
                            Title = "Post 22",
                            TopicId = 3,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 23,
                            Content = "post1post2post3post4",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9866),
                            PhotoPath = "images/23.jpg",
                            Title = "Post 23",
                            TopicId = 3,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 24,
                            Content = "this is a random content",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(9878),
                            PhotoPath = "images/24.jpg",
                            Title = "Post 24",
                            TopicId = 1,
                            UserId = 1,
                            Visible = true
                        });
                });

            modelBuilder.Entity("Domain.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId", "PostId")
                        .IsUnique();

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(5584),
                            PostId = 1,
                            UserId = 1,
                            Value = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 871, DateTimeKind.Local).AddTicks(5754),
                            PostId = 2,
                            UserId = 2,
                            Value = 9,
                            Visible = true
                        });
                });

            modelBuilder.Entity("Domain.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 858, DateTimeKind.Local).AddTicks(742),
                            Name = "Topic 1",
                            Visible = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 865, DateTimeKind.Local).AddTicks(2316),
                            Name = "Topic 2",
                            Visible = true
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 865, DateTimeKind.Local).AddTicks(2466),
                            Name = "Topic 3",
                            Visible = true
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 865, DateTimeKind.Local).AddTicks(2479),
                            Name = "Topic 4",
                            Visible = true
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 865, DateTimeKind.Local).AddTicks(2490),
                            Name = "Topic 5",
                            Visible = true
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 865, DateTimeKind.Local).AddTicks(2510),
                            Name = "Topic 6",
                            Visible = true
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 865, DateTimeKind.Local).AddTicks(2521),
                            Name = "Topic 7",
                            Visible = true
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 865, DateTimeKind.Local).AddTicks(2530),
                            Name = "Topic 8",
                            Visible = true
                        });
                });

            modelBuilder.Entity("Domain.UseCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("UseCases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Create User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Soft Delete User"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Update User"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Create Topic"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Soft Delete Topic"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Update Topic"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Create Post"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Soft Delete Post"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Update Post"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Create Rating"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Update Rating"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Create Comment"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Soft Delete Comment"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Update Comment"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Search UseCaseLog"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Search Topics"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Search Posts"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Get One Topic"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Get One Post"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Search Comments"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Get One Comment"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Search Users"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Get One User"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Search Ratings"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Get One Rating"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Create UseCase"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Update UseCase"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Search UseCases"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Get One UseCase"
                        });
                });

            modelBuilder.Entity("Domain.UseCaseLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("UseCaseId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UseCaseId");

                    b.HasIndex("UserId");

                    b.ToTable("UseCaseLogs");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(3361),
                            Email = "admin@gmail.com",
                            FirstName = "Admin",
                            LastName = "Admin",
                            Password = "7guOFkbnL2s5eA0xSepLNiQdTQ+Rj8Oe0t6HR2KpKlw=",
                            Visible = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 30, 17, 34, 12, 869, DateTimeKind.Local).AddTicks(3624),
                            Email = "User@gmail.com",
                            FirstName = "User",
                            LastName = "User",
                            Password = "7guOFkbnL2s5eA0xSepLNiQdTQ+Rj8Oe0t6HR2KpKlw=",
                            Visible = true
                        });
                });

            modelBuilder.Entity("Domain.UserUseCase", b =>
                {
                    b.Property<int>("UseCaseId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("UseCaseId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserUseCases");
                });

            modelBuilder.Entity("Domain.Comment", b =>
                {
                    b.HasOne("Domain.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Post", b =>
                {
                    b.HasOne("Domain.Topic", "Topic")
                        .WithMany("Posts")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Rating", b =>
                {
                    b.HasOne("Domain.Post", "Post")
                        .WithMany("Ratings")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.UseCaseLog", b =>
                {
                    b.HasOne("Domain.UseCase", "UseCase")
                        .WithMany("UseCaseLogs")
                        .HasForeignKey("UseCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany("UseCaseLogs")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Domain.UserUseCase", b =>
                {
                    b.HasOne("Domain.UseCase", "UseCase")
                        .WithMany("UserUseCases")
                        .HasForeignKey("UseCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany("UserUseCases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
