// <auto-generated />
using System;
using EFDataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFDataAccess.Migrations
{
    [DbContext(typeof(PhoTexBlogContext))]
    [Migration("20200630153222_added posts")]
    partial class addedposts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Domain.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "post1post1post1post1post1post1post1post1post1post1post1post1post1post1",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(5967),
                            PhotoPath = "images/1.png",
                            Title = "Post 1",
                            TopicId = 6,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 2,
                            Content = "post2post2post2post2post2post2post2post2post2post2post2",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6206),
                            PhotoPath = "images/2.png",
                            Title = "Post 2",
                            TopicId = 6,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 3,
                            Content = "post3post3post3post3post3post3post3",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6226),
                            PhotoPath = "images/3.png",
                            Title = "Post 3",
                            TopicId = 5,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 4,
                            Content = "post4post4post4post4post4post4post4post4post4post4",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6238),
                            PhotoPath = "images/4.png",
                            Title = "Post 4",
                            TopicId = 5,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 5,
                            Content = "post1post1post1post1post1post1post1post1post1post1post1post1post1post1",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6250),
                            PhotoPath = "images/5.png",
                            Title = "Post 5",
                            TopicId = 5,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 6,
                            Content = "post2post2post2post2post2post2post2post2post2",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6269),
                            PhotoPath = "images/6.png",
                            Title = "Post 6",
                            TopicId = 2,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 7,
                            Content = "post3post3post3post3post3post3post3",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6280),
                            PhotoPath = "images/7.png",
                            Title = "Post 7",
                            TopicId = 1,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 8,
                            Content = "post4post4post4post4post4post4post4post4post4",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6292),
                            PhotoPath = "images/8.png",
                            Title = "Post 8",
                            TopicId = 5,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 9,
                            Content = "post1post1post1post1post1post1post1post1",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6304),
                            PhotoPath = "images/9.png",
                            Title = "Post 9",
                            TopicId = 3,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 10,
                            Content = "post2post2post2post2post2post2post2post2post2",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6319),
                            PhotoPath = "images/10.jpg",
                            Title = "Post 10",
                            TopicId = 2,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 11,
                            Content = "post3post3post3post3post3post3post3",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6330),
                            PhotoPath = "images/11.jpg",
                            Title = "Post 11",
                            TopicId = 3,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 12,
                            Content = "post3post3post3post3post3post3post3",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6382),
                            PhotoPath = "images/12.jpg",
                            Title = "Post 12",
                            TopicId = 3,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 13,
                            Content = "post1post2post3post4",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6398),
                            PhotoPath = "images/13.jpg",
                            Title = "Post 13",
                            TopicId = 4,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 14,
                            Content = "post4post4post431",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6410),
                            PhotoPath = "images/14.jpg",
                            Title = "Post 14",
                            TopicId = 7,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 15,
                            Content = "post4post4post431",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6420),
                            PhotoPath = "images/15.jpg",
                            Title = "Post 15",
                            TopicId = 7,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 16,
                            Content = "post1post1post2post3",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6431),
                            PhotoPath = "images/16.jpg",
                            Title = "Post 16",
                            TopicId = 4,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 17,
                            Content = "post1post1post2post3post2",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6443),
                            PhotoPath = "images/17.jpg",
                            Title = "Post 17",
                            TopicId = 5,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 18,
                            Content = "post4post4post4post4post4post4post4",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6460),
                            PhotoPath = "images/18.jpg",
                            Title = "Post 18",
                            TopicId = 4,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 19,
                            Content = "post2post2post2post2",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6470),
                            PhotoPath = "images/19.jpg",
                            Title = "Post 19",
                            TopicId = 3,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 20,
                            Content = "post12post1post1post1post1",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6482),
                            PhotoPath = "images/20.jpg",
                            Title = "Post 20",
                            TopicId = 6,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 21,
                            Content = "post12post1post1post1post4",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6493),
                            PhotoPath = "images/21.jpg",
                            Title = "Post 21",
                            TopicId = 1,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 22,
                            Content = "post1post2post3post4",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6504),
                            PhotoPath = "images/22.jpg",
                            Title = "Post 22",
                            TopicId = 6,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 23,
                            Content = "post1post2post3post4",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6514),
                            PhotoPath = "images/23.jpg",
                            Title = "Post 23",
                            TopicId = 3,
                            UserId = 1,
                            Visible = true
                        },
                        new
                        {
                            Id = 24,
                            Content = "this is a random content",
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 782, DateTimeKind.Local).AddTicks(6526),
                            PhotoPath = "images/24.jpg",
                            Title = "Post 24",
                            TopicId = 6,
                            UserId = 1,
                            Visible = true
                        });
                });

            modelBuilder.Entity("Domain.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId", "PostId")
                        .IsUnique();

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Domain.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 769, DateTimeKind.Local).AddTicks(6414),
                            Name = "Topic 1",
                            Visible = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 775, DateTimeKind.Local).AddTicks(7662),
                            Name = "Topic 2",
                            Visible = true
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 775, DateTimeKind.Local).AddTicks(7763),
                            Name = "Topic 3",
                            Visible = true
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 775, DateTimeKind.Local).AddTicks(7775),
                            Name = "Topic 4",
                            Visible = true
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 775, DateTimeKind.Local).AddTicks(7785),
                            Name = "Topic 5",
                            Visible = true
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 775, DateTimeKind.Local).AddTicks(7804),
                            Name = "Topic 6",
                            Visible = true
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 775, DateTimeKind.Local).AddTicks(7813),
                            Name = "Topic 7",
                            Visible = true
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 775, DateTimeKind.Local).AddTicks(7822),
                            Name = "Topic 8",
                            Visible = true
                        });
                });

            modelBuilder.Entity("Domain.UseCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("UseCases");
                });

            modelBuilder.Entity("Domain.UseCaseLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("UseCaseId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UseCaseId");

                    b.HasIndex("UserId");

                    b.ToTable("UseCaseLogs");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 781, DateTimeKind.Local).AddTicks(6696),
                            Email = "admin@gmail.com",
                            FirstName = "Admin",
                            LastName = "Admin",
                            Password = "7guOFkbnL2s5eA0xSepLNiQdTQ+Rj8Oe0t6HR2KpKlw=",
                            Visible = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 6, 30, 17, 32, 20, 781, DateTimeKind.Local).AddTicks(7222),
                            Email = "User@gmail.com",
                            FirstName = "User",
                            LastName = "User",
                            Password = "7guOFkbnL2s5eA0xSepLNiQdTQ+Rj8Oe0t6HR2KpKlw=",
                            Visible = true
                        });
                });

            modelBuilder.Entity("Domain.UserUseCase", b =>
                {
                    b.Property<int>("UseCaseId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("UseCaseId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserUseCases");
                });

            modelBuilder.Entity("Domain.Comment", b =>
                {
                    b.HasOne("Domain.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Post", b =>
                {
                    b.HasOne("Domain.Topic", "Topic")
                        .WithMany("Posts")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Rating", b =>
                {
                    b.HasOne("Domain.Post", "Post")
                        .WithMany("Ratings")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.UseCaseLog", b =>
                {
                    b.HasOne("Domain.UseCase", "UseCase")
                        .WithMany("UseCaseLogs")
                        .HasForeignKey("UseCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany("UseCaseLogs")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Domain.UserUseCase", b =>
                {
                    b.HasOne("Domain.UseCase", "UseCase")
                        .WithMany("UserUseCases")
                        .HasForeignKey("UseCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany("UserUseCases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
